
try:
  print(a)
except Exception as e:
   print("somthing went wrong please try again later")
   

print("hello")
